---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: localhost:32000/apache
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  externalIPs:
    - 10.0.0.4
  ports:
    - port: 88
      targetPort: 80
      protocol: TCP
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maridb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: localhost:32000/mariadb
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  externalIPs:
    - 10.0.0.4
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: localhost:32000/mysql
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  externalIPs:
    - 10.0.0.4
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: localhost:32000/drupal
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  externalIPs:
    - 10.0.0.4
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: drupal
---